---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/merchants":
    post:
      summary: Register merchant and wallet
      tags:
      - Merchants
      security:
      - BearerAuth: []
      parameters: []
      responses:
        '201':
          description: Created again with another document
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 155
                    legal_name: Segunda Loja
                    document: '02945835487'
                    status: active
                    account:
                      currency: BRL
                      available_balance_cents: 0
                      pending_balance_cents: 0
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
        '422':
          description: Unprocessable Content
          content:
            application/json:
              examples:
                example:
                  value:
                    errors:
                      legal_name:
                      - can't be blank
                      document:
                      - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant:
                  type: object
                  properties:
                    legal_name:
                      type: string
                    document:
                      type: string
                  required:
                  - legal_name
                  - document
              required:
              - merchant
    get:
      summary: List my merchants
      tags:
      - Merchants
      security:
      - BearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 156
                    legal_name: Anderson, Batz and Lind
                    document: '05670444248'
                    status: active
                    account:
                      currency: BRL
                      available_balance_cents: 0
                      pending_balance_cents: 0
                  - id: 157
                    legal_name: Runolfsson Inc
                    document: '03375483821'
                    status: active
                    account:
                      currency: BRL
                      available_balance_cents: 0
                      pending_balance_cents: 0
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
  "/api/v1/merchants/{id}":
    get:
      summary: Get merchant and wallet
      tags:
      - Merchants
      security:
      - BearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 158
                    legal_name: Mraz-Daugherty
                    document: '05886445870'
                    status: active
                    account:
                      currency: BRL
                      available_balance_cents: 1000
                      pending_balance_cents: 500
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Not Found
    patch:
      summary: Update merchant
      tags:
      - Merchants
      security:
      - BearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 160
                    legal_name: Novo Nome
                    document: '04427531288'
                    status: active
                    account:
                      currency: BRL
                      available_balance_cents: 0
                      pending_balance_cents: 0
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Not Found
        '422':
          description: Unprocessable Content
          content:
            application/json:
              examples:
                example:
                  value:
                    errors:
                      legal_name:
                      - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant:
                  type: object
                  properties:
                    legal_name:
                      type: string
              required:
              - merchant
  "/api/v1/me":
    get:
      summary: Get my profile information
      tags:
      - Users
      security:
      - BearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 644
                    email: natasha.maggio@torp.test
                    name: Williams Rippin
                    cpf: '06947106281'
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
    patch:
      summary: Update my profile information
      tags:
      - Users
      security:
      - BearerAuth: []
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 645
                    email: kenna@shields.example
                    name: Novo Nome
                    cpf: '00999005480'
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
        '422':
          description: Unprocessable Content
          content:
            application/json:
              examples:
                example:
                  value:
                    errors:
                      email:
                      - is not a valid address
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    name:
                      type: string
                    cpf:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
              required:
              - user
    delete:
      summary: Delete my account
      tags:
      - Users
      security:
      - BearerAuth: []
      responses:
        '204':
          description: No Content
          content:
            application/json:
              examples:
                example:
                  value: ''
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
  "/api/v1/register":
    post:
      summary: Create a new user account
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              examples:
                example:
                  value:
                    access_token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2NDgsImV4cCI6MTc4NTg1NTAyMn0.cBQ3W-Np1wFtEVVIbyxF-y7_iH5jzwgJJjXWgNEc0VY
                    refresh_token: mnT_7_neZ7Ut6yOLRlUefXZlrNbuuntaEUL-NCO3tDE
                    user:
                      id: 648
                      email: april_jerde@wisozk.test
                      name: Novo Usuario
                      cpf: '08990492815'
        '422':
          description: Unprocessable Content
          content:
            application/json:
              examples:
                example:
                  value:
                    errors:
                      email:
                      - has already been taken
                      cpf:
                      - has already been taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    name:
                      type: string
                    cpf:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                  required:
                  - email
                  - name
                  - cpf
                  - password
                  - password_confirmation
              required:
              - user
  "/api/v1/login":
    post:
      summary: Authenticate user and return token
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                    access_token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2NTAsImV4cCI6MTc4NTg1NTAyMn0.LGVj7oVA5x-0pHRB0uOyXOrvC3r73qynw2UutwWflLg
                    refresh_token: 27clEHnZQW6bY22WORt6HPHqcHq6SCbJCKRwlhyI91Y
                    user:
                      id: 650
                      email: verna@howell-steuber.test
                      name: Rod Legros JD
                      cpf: '02240502304'
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
  "/api/v1/refresh":
    post:
      summary: Refresh access and refresh tokens
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                    access_token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2NTIsImV4cCI6MTc4NTg1NTAyMn0.VweqUbsXguygxRFIxEEBbe6bR-FmsufTyopEeNsLEDs
                    refresh_token: Sn5nUcwnkKJUfXENuGRLXQcl0tnOX7QCzzsX7PQtU8M
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
              required:
              - refresh_token
  "/api/v1/logout":
    delete:
      summary: Logout current user
      tags:
      - Users
      security:
      - BearerAuth: []
      parameters: []
      responses:
        '204':
          description: No Content
          content:
            application/json:
              examples:
                example:
                  value: ''
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
              required:
              - refresh_token
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      in: header
