---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/me":
    get:
      summary: Get my profile information
      tags:
      - Users
      security:
      - BearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 199
                    cpf: '04145968468'
                    email: markus@streich-anderson.example
                    name: Dr. Angel Watsica
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
    patch:
      summary: Update my profile information
      tags:
      - Users
      security:
      - BearerAuth: []
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                    name: Novo Nome
                    email: ronnie.moore@hagenes.example
                    cpf: '06016692239'
                    id: 200
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
        '422':
          description: Unprocessable Content
          content:
            application/json:
              examples:
                example:
                  value:
                    errors:
                      email:
                      - is not a valid address
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    name:
                      type: string
                    cpf:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
              required:
              - user
    delete:
      summary: Delete my account
      tags:
      - Users
      security:
      - BearerAuth: []
      responses:
        '204':
          description: No Content
          content:
            application/json:
              examples:
                example:
                  value: ''
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
  "/api/v1/register":
    post:
      summary: Create a new user account
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              examples:
                example:
                  value:
                    token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyMDMsImV4cCI6MTc4NTgwODI0M30.i4yGMti4xXURacDnYyL3pXISOG5sjxmbWMGI2eKMn84
                    user:
                      id: 203
                      cpf: '02381209298'
                      email: edgardo_kassulke@west.test
                      name: Novo Usuario
        '422':
          description: Unprocessable Content
          content:
            application/json:
              examples:
                example:
                  value:
                    errors:
                      email:
                      - has already been taken
                      cpf:
                      - has already been taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    name:
                      type: string
                    cpf:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                  required:
                  - email
                  - name
                  - cpf
                  - password
                  - password_confirmation
              required:
              - user
  "/api/v1/login":
    post:
      summary: Authenticate user and return token
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                    token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyMDUsImV4cCI6MTc4NTgwODI0M30.Wgh8ah0LRKB_KIu6CqGJG7StOpe2lsN8l8fXWROjSdA
                    user:
                      id: 205
                      cpf: '01544504136'
                      email: alverta@goldner.test
                      name: Letha Lynch JD
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
  "/api/v1/logout":
    delete:
      summary: Logout current user
      tags:
      - Users
      security:
      - BearerAuth: []
      responses:
        '204':
          description: No Content
          content:
            application/json:
              examples:
                example:
                  value: ''
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      in: header
